app/urls.py
from django.urls import path
from . import views

app_name = 'app'


urlpatterns = [
    path('', views.ListAndList.as_view(), name='list_and_list'),
    path('create/', views.ListAndCreate.as_view(), name='list_and_create'),
    path('detail/<int:pk>/', views.DetailAndCreate.as_view(), name='detail_and_create'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models


class Category(models.Model):
    """カテゴリー"""
    name = models.CharField('カテゴリ名', max_length=255)

    def __str__(self):
        return self.name


class Post(models.Model):
    """記事"""
    title = models.CharField('タイトル', max_length=30)
    category = models.ForeignKey(Category, verbose_name='カテゴリ', on_delete=models.PROTECT)

    def __str__(self):
        return self.title


class Comment(models.Model):
    """コメント"""
    text = models.CharField('コメント内容', max_length=100)
    post = models.ForeignKey(Post, verbose_name='紐づく記事', on_delete=models.PROTECT)

    def __str__(self):
        return self.text

app/forms.py
from django import forms
from .models import Comment


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': forms.TextInput(attrs={'class': 'form-control'})
        }

app/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import ModelFormMixin
from django.views import generic
from .forms import CommentCreateForm
from .models import Post, Category


class ListAndList(generic.ListView):
    model = Post
    template_name = 'app/post_list_and_category_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        return context


class ListAndCreate(generic.ListView, ModelFormMixin):
    model = Post
    fields = '__all__'
    success_url = reverse_lazy('app:list_and_create')  # このビュー自身!
    template_name = 'app/post_list_and_post_create.html'

    def get(self, request, *args, **kwargs):
        self.object = None
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = None
        self.object_list = self.get_queryset()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class DetailAndCreate(ModelFormMixin, generic.DetailView):
    model = Post
    form_class = CommentCreateForm
    template_name = 'app/post_detail_and_comment_create.html'

    def form_valid(self, form):
        post_pk = self.kwargs['pk']
        comment = form.save(commit=False)
        comment.post = get_object_or_404(Post, pk=post_pk)
        comment.save()
        return redirect('app:detail_and_create', pk=post_pk)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            self.object = self.get_object()
            return self.form_invalid(form)

app/templates/app/base.html
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>
<body>
    <div class="container mt-3">
        {% block content %}{% endblock %}
    </div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
        integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
        crossorigin="anonymous"></script>
</body>
</html>

app/templates/app/post_detail_and_comment_create.html
{% extends 'app/base.html' %}

{% block content %}
<h1>{{ post.title }}</h1>
<p>カテゴリ:{{ post.category }}</p>
<hr>


{% for comment in post.comment_set.all %}
    <p>{{ comment }}</p>
{% endfor %}
<hr>

<form action="" method="POST">
  {{ form.non_field_errors }}
  {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
  {% endfor %}
  {% csrf_token %}
  <button type="submit" class="btn btn-primary">送信</button>
</form>


{% endblock %}

app/templates/app/post_list_and_category_list.html
{% extends 'app/base.html' %}

{% block content %}
<h2>記事一覧</h2>
<table class="table">
    {% for post in post_list %}
        <tr>
            <td>{{ post.title }}</td>
            <td>{{ post.category }}</td>
        </tr>
    {% endfor %}
</table>

<h2>カテゴリ一覧</h2>
<table class="table">
    {% for category in category_list %}
        <tr>
            <td>{{ category.name }}</td>
        </tr>
    {% endfor %}
</table>


{% endblock %}

app/templates/app/post_list_and_post_create.html
{% extends 'app/base.html' %}

{% block content %}
<h2>記事一覧</h2>
<table class="table">
    {% for post in post_list %}
        <tr>
            <td>{{ post.title }}</td>
            <td>{{ post.category }}</td>
        </tr>
    {% endfor %}
</table>

<h2>記事作成</h2>
<form action="" method="POST">
  {{ form.non_field_errors }}
  {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
  {% endfor %}
  {% csrf_token %}
  <button type="submit" class="btn btn-primary">送信</button>
</form>

{% endblock %}